[tool.poetry]
name = "extraction-openai-functions"
version = "0.1.0"
description = ""
authors = ["Lance Martin <lance@langchain.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.323"
openai = ">=0.27.9"

[tool.langserve]
export_module = "exctraction_openai_functions"
export_attr = "chain"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
