[tool.poetry]
name = "rag-singlestoredb"
version = "0.0.1"
description = "RAG using SingleStoreDB"
authors = ["Alex Peng <apeng@singlestore.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
singlestoredb = ">=0.8.1"
tiktoken = "^0.5.1"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_singlestoredb"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "SingleStoreDB"
integrations = ["OpenAI", "SingleStoreDB"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
