[tool.poetry]
name = "neo4j-cypher-memory"
version = "0.1.0"
description = ""
authors = [
    "Tomaz Bratanic <tomaz.bratanic@neo4j.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
neo4j = ">5.12"
openai = "^0.28.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "neo4j_cypher_memory"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
