[tool.poetry]
name = "shopping-assistant"
version = "0.0.1"
description = "A template for a shopping assistant agent"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.12,<4.0"
langchain = "^0.1"
openai = "<2"
ionic-langchain = "^0.2.2"
langchain-openai = "^0.0.5"
langchainhub = "^0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.20"

[tool.langserve]
export_module = "shopping_assistant.agent"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "chatbot"
author = "LangChain"
integrations = ["Ionic"]
tags = ["conversation", "agents"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
