# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# and
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directories:
      - "/libs/core/"
      - "/libs/langchain/"
      - "/libs/langchain_v1/"
    schedule:
      interval: "weekly"
    groups:
      langchain-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/libs/partners/anthropic/"
      - "/libs/partners/chroma/"
      - "/libs/partners/deepseek/"
      - "/libs/partners/exa/"
      - "/libs/partners/fireworks/"
      - "/libs/partners/groq/"
      - "/libs/partners/huggingface/"
      - "/libs/partners/mistralai/"
      - "/libs/partners/nomic/"
      - "/libs/partners/ollama/"
      - "/libs/partners/openai/"
      - "/libs/partners/perplexity/"
      - "/libs/partners/qdrant/"
      - "/libs/partners/xai/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      partner-deps:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/libs/text-splitters/"
      - "/libs/standard-tests/"
      - "/libs/model-profiles/"
    schedule:
      interval: "weekly"
    groups:
      other-deps:
        patterns:
          - "*"
