[tool.poetry]
name = "self-query-supabase"
version = "0.1.0"
description = "QA with Supabase using natural language"
authors = [
    "Greg Richardson <greg@supabase.io>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
tiktoken = "^0.5.1"
supabase = "^1.2.0"
lark = "^1.1.8"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
[tool.poetry.group.dev.dependencies.python-dotenv]
extras = [
    "cli",
]
version = "^1.0.0"

[tool.langserve]
export_module = "self_query_supabase.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Supabase"
integrations = ["OpenAI", "Supabase"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
