[tool.poetry]
name = "xml-agent"
version = "0.1.0"
description = "Agent that uses XML syntax to communicate its decisions of what actions to take"
authors = ["Lance Martin <lance@langchain.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
langchainhub = ">=0.1.13"
duckduckgo-search = "^3.8.3"
langchain-anthropic = "^0.1.4"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "xml_agent"
export_attr = "agent_executor"

[tool.templates-hub]
use-case = "agent"
author = "LangChain"
integrations = ["Anthropic"]
tags = ["agents"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
