[tool.poetry]
name = "stepback-qa-prompting"
version = "0.0.1"
description = "Use Step-Back prompting to improve retrieval"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
duckduckgo-search = "^3.9.3"
openai = "<2"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "stepback_qa_prompting.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI"]
tags = ["paper"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
