[tool.poetry]
name = "self-query-qdrant"
version = "0.1.0"
description = "Self-querying retriever using Qdrant"
authors = ["Kacper ≈Åukawski <lukawski.kacper@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "self_query_qdrant"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langchain = "^0.1"
qdrant-client = ">=1.6"
lark = "^1.1.8"
tiktoken = "^0.5.1"
langchain-openai = "^0.0.8"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
[tool.poetry.group.dev.dependencies.python-dotenv]
extras = [
    "cli",
]
version = "^1.0.0"

[tool.langserve]
export_module = "self_query_qdrant"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Qdrant"
integrations = ["Qdrant", "OpenAI"]
tags = ["research", "agents"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
