[tool.poetry]
name = "rag-gpt-crawler"
version = "0.1.0"
description = "Use gpt-crawler to build a chat app for any website"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_gpt_crawler"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Google"
integrations = ["OpenAI", "Chromadb"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
