blank_issues_enabled: false
version: 2.1
contact_links:
  - name: ðŸ“š Documentation issue
    url: https://github.com/langchain-ai/docs/issues/new?template=01-langchain.yml
    about: Report an issue related to the LangChain documentation
  - name: ðŸ’¬ LangChain Forum
    url:  https://forum.langchain.com/
    about: General community discussions and support
  - name: ðŸ“š LangChain Documentation
    url: https://docs.langchain.com/oss/python/langchain/overview
    about: View the official LangChain documentation
  - name: ðŸ“š API Reference Documentation
    url: https://reference.langchain.com/python/
    about: View the official LangChain API reference documentation
  - name: ðŸ’¬ LangChain Forum
    url: https://forum.langchain.com/
    about: Ask questions and get help from the community
