[tool.poetry]
name = "rag-google-cloud-sensitive-data-protection"
version = "0.0.1"
description = "RAG using sensitive data protection"
authors = ["Juan Calvo <juan.calvo@datatonic.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
google-cloud-aiplatform = ">=1.35.0"
google-cloud-dlp = "^3.13.0"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_google_cloud_sensitive_data_protection"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Datatonic"
integrations = ["OpenAI", "Google Cloud"]
tags = ["data"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
