[tool.poetry]
name = "sql-pgvector"
version = "0.0.1"
description = "Use pgvector for combining postgreSQL with semantic search / RAG"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
psycopg2 = "^2.9.9"
tiktoken = "^0.5.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "sql_pgvector"
export_attr = "chain"

[tool.templates-hub]
use-case = "sql"
author = "LangChain"
integrations = ["OpenAI"]
tags = ["sql"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
