[tool.poetry]
name = "astradb_entomology_rag"
version = "0.0.1"
description = ""
authors = [
    "Stefano Lottini <stefano.lottini@datastax.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
openai = "^0.28.1"
tiktoken = "^0.5.1"
astrapy = "^0.5.3"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "astradb_entomology_rag"
export_attr = "chain"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
