[tool.poetry]
name = "rag-self-query"
version = "0.0.1"
description = "RAG with metadata filtering using self-query retriever on Elasticsearch vector store"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = ">=0.0.335"
openai = "<2"
elasticsearch = "^8.10.0"
sentence-transformers = "^2.2.2"
jq = "^1.6.0"
tiktoken = "^0.5.1"
lark = "^1.1.8"
pydantic = "^2.4.2"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Elasticsearch"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core",]
build-backend = "poetry.core.masonry.api"
