[tool.poetry]
name = "rag-pinecone-rerank"
version = "0.1.0"
description = ""
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = ">=0.0.325"
openai = "<2"
tiktoken = ">=0.5.1"
pinecone-client = ">=2.2.4"
cohere = ">=4.32"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Pinecone", "Cohere"]
tags = ["vectordbs","post-processing"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
