[tool.poetry]
name = "rag-gemini-multi-modal"
version = "0.1.0"
description = "Multi-modal RAG using Gemini and OpenCLIP embeddings"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langchain = ">=0.0.350"
openai = "<2"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
open-clip-torch = ">=2.23.0"
torch = ">=2.1.0"
pypdfium2 = ">=4.20.0"
langchain-experimental = "^0.0.43"
langchain-google-genai = ">=0.0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "rag_gemini_multi_modal"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Chroma"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
