[tool.poetry]
name = "rag-multi-modal-local"
version = "0.1.0"
description = "Multi-modal RAG using Chroma"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.353,<0.2"
openai = "<2"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
open-clip-torch = ">=2.23.0"
torch = ">=2.1.0"
langchain-experimental = ">=0.0.43"
langchain-community = ">=0.0.4"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_multi_modal_local"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["Ollama", "Chroma"]
tags = ["multi-modal"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
