[tool.poetry]
name = "rag-codellama-fireworks"
version = "0.1.0"
description = "RAG using OSS LLMs via Fireworks"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langchain = "^0.1"
gpt4all = ">=1.0.8"
tiktoken = ">=0.5.1"
chromadb = ">=0.4.14"
fireworks-ai = ">=0.6.0"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_codellama_fireworks"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Elastic"
integrations = ["OpenAI", "Fireworks"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
