[tool.poetry]
name = "rewrite-retrieve-read"
version = "0.0.1"
description = "Query transformation using the rewrite-retrieve-read to improve retrieval"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
duckduckgo-search = "^3.9.3"
openai = "<2"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rewrite_retrieve_read.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI"]
tags = ["paper", "prompt-hub"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
