[tool.poetry]
name = "rewrite_retrieve_read"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.313"
duckduckgo-search = "^3.9.3"

[tool.langserve]
export_module = "rewrite_retrieve_read.chain"
export_attr = "chain"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
