[tool.poetry]
name = "rag-fusion"
version = "0.0.1"
description = "RAG using RAG fusion approach"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "<2"
pinecone-client = "^2.2.4"
langchainhub = "^0.1.13"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_fusion.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Pinecone"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
