[tool.poetry]
name = "rag-elasticsearch"
version = "0.0.1"
description = "RAG using Elasticsearch"
authors = [
    "Joe McElroy <joseph.mcelroy@elastic.co>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langchain = "^0.1"
langchain-elasticsearch = "^0.1.0"
openai = "<2"
sentence-transformers = "^2.2.2"
jq = "^1.6.0"
tiktoken = "^0.5.1"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_elasticsearch"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Elastic"
integrations = ["OpenAI", "Elasticsearch"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
