[tool.poetry]
name = "guardrails-output-parser"
version = "0.0.1"
description = "Use guardrails-ai to validate LLM output"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langchain = "^0.1"
openai = "<2"
guardrails-ai = "^0.2.4"
alt-profanity-check = "^1.3.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "guardrails_output_parser.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "validation"
author = "LangChain"
integrations = ["Guardrails", "OpenAI"]
tags = ["moderation"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
