[tool.poetry]
name = "rag-momento-vector-index"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = ">=0.0.313, <0.1"
momento = "^1.12.0"
openai = "<2"
tiktoken = "^0.5.1"

[tool.poetry.group.dev.dependencies]
gigachain-cli = ">=0.0.15"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.poetry.group.index.dependencies]
bs4 = "^0.0.1"

[tool.poetry.group.test.dependencies]
gigaserve = "^0.0.21"

[tool.gigaserve]
export_module = "rag_momento_vector_index"
export_attr = "chain"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
