[tool.poetry]
name = "rag-opensearch"
version = "0.0.1"
description = "RAG template for OpenSearch"
authors = ["Kalyan Reddy <kalyan.ben10@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"
openai = "^0.28.1"
opensearch-py = "^2.0.0"
tiktoken = "^0.5.1"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_opensearch"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "OpenSearch"
integrations = ["OpenAI", "OpenSearch"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
