[tool.poetry]
name = "openai-functions-agent"
version = "0.1.0"
description = ""
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = ">=0.0.325"
openai = "^0.28.1"
tavily-python = "^0.1.9"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[tool.langserve]
export_module = "openai_functions_agent"
export_attr = "agent_executor"

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
