[tool.poetry]
name = "rag-redis"
version = "0.0.1"
description = "Run a RAG app backed by OpenAI, HuggingFace, and Redis as a vector database"
authors = [
    "Tyler Hutcherson <tyler.hutcherson@redis.com>",
    "Sam Partee <sam.partee@redis.com>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
langchain = "^0.1"
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"
openai = "<2"
sentence-transformers = "2.2.2"
redis = "5.0.1"
tiktoken = "0.5.1"
pdf2image = "1.16.3"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.dependencies.unstructured]
version = "^0.10.27"
extras = ["pdf"]

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.24.1"
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_redis.chain"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Redis"
integrations = ["OpenAI", "Redis", "HuggingFace"]
tags = ["vectordbs"]

[tool.poe.tasks.start]
cmd = "uvicorn langchain_cli.dev_scripts:create_demo_server --reload --port $port --host $host"
args = [
    { name = "port", help = "port to run on", default = "8000" },
    { name = "host", help = "host to run on", default = "127.0.0.1" },
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
