[tool.poetry]
name = "sql-ollama"
version = "0.1.0"
description = "Private QA with a SQL database using natural language and a local LLM"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "sql_ollama"
export_attr = "chain"

[tool.templates-hub]
use-case = "sql"
author = "LangChain"
integrations = ["Ollama"]
tags = ["sql"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
