---
name: libs/langchain CI

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - '.github/workflows/_lint.yml'
      - '.github/workflows/_test.yml'
      - '.github/workflows/langchain_ci.yml'
      - 'libs/langchain/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  lint:
    uses:
      ./.github/workflows/_lint.yml
    with:
      working-directory: libs/langchain
    secrets: inherit
  test:
    uses:
      ./.github/workflows/_test.yml
    with:
      working-directory: libs/langchain
    secrets: inherit